<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IXDM7J5B3" ignored="0" name="Default test" tests="9" failures="1" timestamp="2022-05-27T17:15:59 IST" time="135.479" errors="0">
  <testcase name="runScenario" time="16.04" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="18.052" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="11.232" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="11.885" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="22.541" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="6.373" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="11.328" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [Loan Request Processed] but found [Apply for a Loan]">
      <![CDATA[java.lang.AssertionError: expected [Loan Request Processed] but found [Apply for a Loan]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at stepdefinition.RequestLoan.verify_that_user_is_able_to_request_loan(RequestLoan.java:35)
at âœ½.Verify that user is able to request loan(file:///C:/Users/703316032/Eclipse/CucumberProject/resources/features/RequestLoan.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="24.569" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="12.908" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
</testsuite> <!-- Default test -->
